# SipBan Configuration File

# Parameters to connect to Asterisk AMI
[ami]
port = "5038"
user = "sipban"
pass = "getout"
host = "127.0.0.1"
ping = 600

# Port to send commands
[control]
port = "4451"

# Timers
[timer]
ban = 3600

#Iptables rules actions config
[iptables]
# In this example, we have this iptable rule in table "filter", change
# according your preferences:
#
#     iptables -t filter -A INPUT -i eno1 -p UDP -m udp --dport 5060 -j ACCEPT

path  = "/sbin/"
chain = "sipban-udp"
# to block udp port 5060, you can block all but test
# with caution to avoid lost total access to your system.
scope = "-p udp --dport 5060"
# for SIP over TCP, WS and WSS :
scope_tcp = "-p tcp -m multiport --dports 5060,8088,8089"
#rule  = "REJECT --reject-with icmp-port-unreachable"
rule  = "DROP"
#rule6  = "REJECT --reject-with icmp6-port-unreachable"
rule6  = "DROP"
white_list = "/etc/sipban.wl"
dump = "/etc/sipban.dump"

# Log file
[log]
file = "/var/log/sipban.log"

# Invite Flood Attacks : leave it disabled
# It may ban many legitimate behaviors like :
# - phones that flood the server with SUBSCRIBE requests
# - DECT that flood the server with REGISTER request
# - if all your endpoints have the same remote IP and just exist
[flood]
enabled=0
count=1000
interval=1

# If a 401 Unauthorized is not answered within the grace period, the IP is banned
[noauth]
enabled=1
graceperiod=5
baninterval=0.5